# Documentation: http://docs.travis-ci.com/user/languages/julia/

language: julia

os:
  - linux
  - osx

julia:
  - 1.1
  - 1.2
  - 1.3
  - 1.4
  - nightly

notifications:
  email: false

env:
  global:
    - DOCUMENTER_DEBUG=true

script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - travis_wait 20 julia --project -e 'using Pkg; Pkg.instantiate(); Pkg.build(; verbose = true); Pkg.test(; coverage=true)';

jobs:
  allow_failures:
    - julia: nightly
  include:
    - stage: "Documentation"
      julia: 1.4
      os: linux
      script:
        - julia --project=docs/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd())); Pkg.instantiate()'
        - julia --project=docs/ docs/make.jl
      after_success: skip

after_success:
  - julia -e 'import Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'

sudo: false
